server:
  port: 8080



spring:

  datasource:
    druid:
      url: jdbc:mysql://localhost:3306
      username: root
      password: xjk,929686415

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    map-underscore-to-camel-case: true

# Logger Config
logging:
  level:
    com.hexadecimal: debug

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui/index.html

